apiVersion: v1
kind: Service
metadata:
  name: xds-ext
  namespace: istio-system
spec:
  type: LoadBalancer
  selector:
    istio: pilot
  ports:
  - name: grpc-xds
    port: 15010
    protocol: TCP
    targetPort: 15010
  - name: https-xds
    port: 15011
    protocol: TCP
    targetPort: 15011
  - name: xds-tcp
    port: 15012
    protocol: TCP
    targetPort: 15012
